apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod2
  labels:
    name: MyApp
spec:
  containers:
    - name: myapp-container2
      image: busybox:1.28
      command: ['sh', '-c', 'echo the app is running && sleep 3600']
      env:
        - name: FIRSTNAME
          valueFrom:
            configMapKeyRef:
              name: app-cm
              key: firstname

        - name: SECONDNAME
          valueFrom:
            configMapKeyRef:
              name: app-cm
              key: secondname

