apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  labels:
    app: nginx1
spec:
  nodeName: k8s-node2.cricbuzz.net
  containers:
    - name: nginx-ctrx
      image: nginx:latest
      ports:
        - containerPort: 80
