apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-pod
  name: nginx-pod
spec:
  containers:
    - name: nginx-pod
      image: my-registry:5000/nginx:v1
      resources: {}
  dnsPolicy: ClusterFirst
  imagePullSecrets:
    - name: nginx-secret
  restartPolicy: Always
status: {}
