apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
    tier: frontend
    type: app1
  name: nginx
  namespace: default
spec:
  containers:
  - image: nginx
    name: nginx
  nodeName: espn-cluster-worker
