apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployment/nginx-new
  name: deployment/nginx-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment/nginx-new
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment/nginx-new
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
